import cn from "classnames";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "@/common";
import { ScrollToTop } from "@/components";
import { layoutStyles } from "@/styles";
import "../assets/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Marnien Cueba | Portfolio",
  description: "Generated by create next app",
};

const lexend = localFont({
  src: [
    { path: "../../public/assets/fonts/Lexend/Lexend-VariableFont_wght.ttf" },
  ],
  variable: "--font-lexend",
});

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  const { root } = layoutStyles;
  return (
    <html lang="en" className={cn(lexend.variable, root.base)}>
      <body>
        <Header />
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
