import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ScrollToTop } from '@/components'
// import { Header } from '@/common'
import '../assets/styles.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Marnien Cueba | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        {children}
        <ScrollToTop />
      </body>
    </html>
  )
}
